# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3893ecf698ff0cfa715a9e83838f52cb6a2d929a477fba9200e38c5425840a266b7f68adc462729fa9d528c5c7e2a048e1b58775509670a643d387d83dd97ac0

test:
  secret_key_base: 835b2eae8c5bf3dfaf981e460445d3d691f8c47dd71efe778a20589938e2196cddcad3ac500c11cd26b1c93561a443862a30a7edb6cc2b5cd36c00d17c6322be

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
